### ISSUE TITLE
Вопросы по заданию

### ISSUE THREAD

**Issue by NikolayWTF** [NexignBootcamp/Test-for-all-data-record#2]
Здравствуйте @NexignBootcamp
Есть несколько уточняющих вопросов:

1. Что делать с неполными минутами? Отбрасывать, обсчитывать или округлять до полной минуты? Допустим у абонента поминутный тариф, его разговор длится 4 минуты 6 секунд, в таком случае стоимость разговора будет 4*1,5 = 6 или 4,1 * 1,5 = 6,15 или 5 * 1,5 = 7,5?
2. У абонента тариф "Безлимит 300". Первые 300 минут - это только исходящие звонки или исходящие + входящие?
Заранее спасибо)

**Comment by m1hail1337** [comment]
Может ли один телефонный номер совершать звонки по разным тарифам?

**Comment by NexignBootcamp** [comment]
> Здравствуйте @NexignBootcamp Есть несколько уточняющих вопросов:
> 
> 1. Что делать с неполными минутами? Отбрасывать, обсчитывать или округлять до полной минуты? Допустим у абонента поминутный тариф, его разговор длится 4 минуты 6 секунд, в таком случае стоимость разговора будет 4*1,5 = 6 или 4,1 * 1,5 = 6,15 или 5 * 1,5 = 7,5?
> 2. У абонента тариф "Безлимит 300". Первые 300 минут - это только исходящие звонки или исходящие + входящие?
>    Заранее спасибо)

Привет! 

1. Минуты округляются в большую сторону. В примере если разговор длиться 4 минуты 6 секунд - это будет 5 минут, т.к. уже пошло время внутри пятой минуты. 
2. У всех операторов связи входящие бесплатно (кроме роуминга, но этого нет в задаче) поэтому только **исходящие**.

**Comment by NexignBootcamp** [comment]
Отдельно добавлю, что при проверке учтем варианты где округление было посчитано в меньшую сторону и даже с платными входящими 😄 не переживайте. 

В данном случае важнее ваш подход и логика решения задачи.

**Comment by NikolayWTF** [comment]
@NexignBootcamp Спасибо)
